# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent
align=center
separator_block_width=20


[wind]
#label=🌀
command=~/.config/i3/curl_wind.sh
markup=pango
interval=60

[disk]
command=~/.config/i3/i3blocks-contrib/disk/disk
label=🖪  
interval=30

[wifi]
command=~/.config/i3/i3blocks-contrib/wifi/wifi
label=  
interval=5

[nm-vpn]
command=~/.config/i3/i3blocks-contrib/nm-vpn/nm-vpn
label=  
interval=20


[ip]
command=hostname -I | awk '{ print $1 }'
interval=5
label=🖧  

[volume]
command=~/.config/i3/i3blocks-contrib/volume/volume
interval=1
label=  
signal=10

[temperature]
command=~/.config/i3/i3blocks-contrib/temperature/temperature
label=  
interval=5

[battery2]
command=~/.config/i3/i3blocks-contrib/battery2/battery2
markup=pango
interval=30

[date]
command=date +"%Y-%m-%d   %H:%M"
label= 
interval=1
